namespace RestApiAssesment.Model
{
    public class Product
    {
        public int Id { get; set; } // Auto-generated by SQL Server
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int StockAvailable { get; set; }
    }
}
